vmware-tanzu/vsphere-kubernetes-drivers-operator

- README.md
> /kind documentation
Add Code Coverage Badge and GoReport Badge to show the health of the project
> Add Code Coverage Badge and GoReport Badge for the project

- README.md
- docs/architecture/README.md
- docs/architecture/vdo-architecture.md
/kind documentation
Adds the arch link in the Readme, also adds a placeholder for all the design documents in `docs/architecture`
Fixes #40
> Add arch link in the main README

- controllers/vdoconfig_controller.go
- controllers/vdoconfig_controller_test.go
- pkg/client/dynamic_client.go
- pkg/client/dynamic_client_test.go
- vdoctl/cmd/deploy.go
- vdoctl/cmd/update_matrix.go
/kind bug fix
This PR adds logic to delete the old deployment in case of an upgrade.
Fixes #32 
/kind TESTED
//TODO
> Fix reconcile issue for upgrade scenario

- artifacts/vanilla/vdo-spec.yaml
- vdoctl/cmd/compat.go
- vdoctl/cmd/configure.go
- vdoctl/cmd/deploy.go
- vdoctl/cmd/drivers.go
- vdoctl/cmd/root.go
- vdoctl/cmd/status.go
/kind bug fix
This PR fixes the following: 
1. added validation for VC IP 
2. displays StorageProvider section only when CloudProvider is not configured
Fixes #
> Fixes issues with VCIP validation and vdoctl status command

- vdoctl/cmd/compat.go
/kind bug fix
This PR brings in support for updating compatibility matrix ConfigMap.
Fixes #48
> adding support for compatibility configMap update

- docs/configure_drivers.md
/kind bug fix
updates the documentation to show a different kubelet Path instead of the default one (/var/lib/kubelet).
> update the documentation for CustomKubeletPath

- artifacts/vanilla/vdo-spec.yaml
- config/manager/manager.yaml
- controllers/vdoconfig_controller.go
- controllers/vdoconfig_controller_test.go
/kind bug fix
This PR takes the current namespace from POD and then watches for ConfigMap and VDOConfigResource on that namespace.
Fixes #102 
/kind TESTED
> Use the current namespace instead of hardcoded ones

- controllers/vdoconfig_controller_test.go
- vdoctl/cmd/configure_matrix.go
- vdoctl/cmd/delete.go
- vdoctl/cmd/drivers.go
- vdoctl/cmd/root.go
- vdoctl/cmd/status.go
- vdoctl/cmd/update_matrix.go
- vdoctl/cmd/version.go
/kind bug fix
This PR checks the vdoctl deployment and use the namespace from there.
Fixes #102 
/kind TESTED
> Use current namespace of VdoController in vdoctl

- docs/developer-guide.md
> /kind documentation
Developer guide for VDO containing the following details :
-  Setting up the developer env
-  Building the code from source
-  Running the Test Cases
-  Raising the PR and doing the pre-checks
Fixes #52 
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> Add the Developer Guide for VDO

- artifacts/vanilla/vdo-spec.yaml
Update the artifacts with new Harbor image for vdo-controller
> Update the vdo-spec.yaml with new harbor image

- docs/configure_drivers.md
This PR brings in changes in the documentation for configuring drivers.
Fixes #
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED
> updating docs with vdoctl configure drivers command

- controllers/vdoconfig_controller.go
- controllers/vdoconfig_controller_test.go
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement
Fixes #
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED
> Replaces kubelet path in liveness probe. This is observed in csi 2.4+

- .github/workflows/BuildAndDeploy.yml
Update GoReportCard at every run, earlier this was a manual process which ended up not refreshing the GoReportCard for almost a year.
> Update goReportCard at every run

- controllers/vdoconfig_controller.go
- controllers/vdoconfig_controller_test.go
> Add missing Unit Test for Controllers

- .codecov.yml
Add codecov.yml to include partials
> Add codecove yaml configuration file

- .codecov.yml
- controllers/vdoconfig_controller_test.go
> Add UT's for Controller

- controllers/vdoconfig_controller_test.go
> Add Controller Unit Test and remove flaky test

- controllers/vdoconfig_controller_test.go
- controllers/vspherecloudconfig_controller_test.go
Add Unit Test for Error handling
> Add Unit Test for Controller for handling Error Scenarios

- controllers/vdoconfig_controller_test.go
- pkg/client/dynamic_client_test.go
- pkg/drivers/csi/csiutil_test.go
Covering Error Scenarios for multiple packages
> Unit Test covering Error Scenarios

- controllers/vdoconfig_controller.go
- controllers/vdoconfig_controller_test.go
1. error in fetching cloud config resource
2. testing node providerID reconcile
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
Fixes #
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED
> adds unit test for few error scenarios

- go.mod
- go.sum
Fix dependencies because of CVE vulnerability
> Fix vulnerable dependencies
